services:
  # Frontend - Angular Application
  frontend:
    build:
      context: ./frontend-skeleton
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend
    environment:
      - API_BASE_URL=http://backend:5000
    networks:
      - intelliinspect-network

  # Backend - .NET Core API
  backend:
    build:
      context: ./Backend/IntelliInspect.Backend
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - ml-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=(localdb)\\mssqllocaldb;Database=IntelliInspectDb;Trusted_Connection=true;MultipleActiveResultSets=true
      - MLService__BaseUrl=http://ml-service:8000
    networks:
      - intelliinspect-network

  # ML Service - Python FastAPI
  ml-service:
    build:
      context: ./ml-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ml-models:/app/models
    networks:
      - intelliinspect-network

volumes:
  ml-models:

networks:
  intelliinspect-network:
    driver: bridge
